### ISSUE TITLE
Error/Question --   "isTrusted": true

### ISSUE THREAD

**Issue by stlbucket** [Dodobibi/postgraphile-nuxt#2]
Is there something I am missing?  

following these instructions: https://postgraphile.org/postgraphile/next/subscriptions/

In Ruru, I am seeing this error when I try to execute the subscription:
<img width="1664" alt="image" src="https://github.com/Dodobibi/postgraphile-nuxt/assets/2467892/7591eb89-59f6-41bb-b878-3c5350d9146e">

from my graphile.config.ts:
<img width="229" alt="image" src="https://github.com/Dodobibi/postgraphile-nuxt/assets/2467892/3a278706-513d-486f-82b9-9378a525e66e">

my plugin is slightly modified:
``` ts
import { makeExtendSchemaPlugin, gql } from "postgraphile/utils";
import { context, lambda, listen } from "postgraphile/grafast";
import { jsonParse } from "postgraphile/@dataplan/json";
import { EXPORTABLE } from "graphile-export";

const TopicMessageSubscriptionPlugin = makeExtendSchemaPlugin(() => {
  return {
    typeDefs: /* GraphQL */ gql`
      extend type Subscription {
        topicMessage(topicId: UUID!): TopicMessageSubscriptionPayload
      }

      type TopicMessageSubscriptionPayload {
        event: String
        sub: Int
        id: Int
      }
    `,
    plans: {
      Subscription: {
        topicMessage: {
          subscribePlan: EXPORTABLE(
            (lambda, context, listen, jsonParse) => (_$root, args) => {
              const $pgSubscriber = context().get("pgSubscriber");
              const $topicId = args.get("topicId");
              const $topic = lambda($topicId, (id) => `topic:${id}:message`);
              return listen($pgSubscriber, $topic, jsonParse);
            },
            [lambda, context, listen, jsonParse]
          ),
          plan($event) {
            return $event;
          },
        },
      },
      TopicMessageSubscriptionPayload: {
        event($event) {
          return $event.get("event");
        },
        sub($event) {
          return $event.get("sub");
        },
        id($event) {
          return $event.get("id");
        },
      },
    },
  };
});

export default TopicMessageSubscriptionPlugin;
```

**Comment by stlbucket** [comment]
<img width="344" alt="image" src="https://github.com/Dodobibi/postgraphile-nuxt/assets/2467892/36e6c2f2-c8f6-42ad-b8be-770a8ae1be19">

if i go with the exact grafserv settings in this repository, then my application still works in general, but i cannot get to the /graphiql route

i see the route in the example AND the serv.ts file:

my /api/graphql.ts:
```
import { postgraphile } from "postgraphile"
import { grafserv } from "grafserv/h3/v1";
import preset from "./graphile.config.js";  

console.log('graphql')
const pgl = postgraphile(preset);
const serv = pgl.createServ(grafserv);

export default defineEventHandler(async (event) => {
  return serv.handleEvent(event)  
})

export { serv }
```
and then /route/graphiql:
<img width="371" alt="image" src="https://github.com/Dodobibi/postgraphile-nuxt/assets/2467892/60405e0b-bd28-454f-86f4-47826ca1624f">

<img width="843" alt="image" src="https://github.com/Dodobibi/postgraphile-nuxt/assets/2467892/7522c6d9-7151-4b40-9c6a-33fe960670de">

**Comment by Dodobibi** [comment]
This implementation is waiting pr.
You must import grafserv from this local file, not from grafserv since it's not again merged.

`import { grafserv } from "./h3/v1";`
